name: Hello World
on:
  push:
    branches:
      - main
      - development
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: |
          echo "A build step is running"
          echo "This is a ${{vars.MY_NAME}}"
          echo "This is a ${{secrets.DOCKER_PASSWORD}}"
